### PR TITLE
[dss/architecture] Remove gRPC layer

### PR DESCRIPTION
**Pull request by mickmis**
This removes the gRPC layer. See issue #822 

See all previous PRs that led to this one for more details:
- #848 
- #852 
- #858
- #870 
- #872 
- #877 
- #880 
- #881 
- #882 
- #887 
- #903

### CODE REVIEW

**Comment by BenjaminPelletier** [comment]
I was able to perform a full deployment of the DSS in this PR including a successful prober run on the deployed DSS, but I had to make a few fixes unrelated to this PR in order to accomplish that.  I've created #907 to incorporate those fixes -- after that PR is merged, I'd like to merge master into this branch again and retest the full deployment at that point just to be on the extra-safe side.  I expect that retest to succeed with zero issues.

I would also like to make a 0.5.0 `dss` release just prior to merging this PR.  Before doing that, I would like to perform the same kind of full DSS deployment test on that pre-905 0.5.0-candidate repo state, and doing that effectively requires #906.

These changes look great and ready to merge once the above items are complete.  Thanks for this huge effort!

**Comment by mickmis** [comment]
> I was able to perform a full deployment of the DSS in this PR including a successful prober run on the deployed DSS

Great news :)

> after that PR is merged, I'd like to merge master into this branch again and retest the full deployment

Please ping me when you'd like me to do the merge or help with anything.

> These changes look great and ready to merge once the above items are complete. Thanks for this huge effort!

Happy to see this work merged soon!

**Comment by BenjaminPelletier** [comment]
0.5.0 is now released and the deployment updates discovered on the first try have now been merged, so I think we're ready to merge master into this branch again (some non-trivial conflicts in `Makefile` from #904).  After that merge, I'll deploy this branch from scratch again and expect to have no issues -- at that point, I intend to consider this branch ready to merge, and will approve & merge unless @barroco would like to also run some tests before doing that.  I expect to merge either Tuesday or Wednesday assuming the master merge can be done Tuesday European time and nothing else substantive comes up.

**Comment by barroco** [comment]
> > 0.5.0 is now released and the deployment updates discovered on the first try have now been merged, so I think we're ready to merge master into this branch again (some non-trivial conflicts in `Makefile` from #904). After that merge, I'll deploy this branch from scratch again and expect to have no issues -- at that point, I intend to consider this branch ready to merge, and will approve & merge unless @barroco would like to also run some tests before doing that. I expect to merge either Tuesday or Wednesday assuming the master merge can be done Tuesday European time and nothing else substantive comes up.
> 
> I created #910 to update this PR with the latest changes from master and conflicts solved.

Thank you very much @mickmis , @BenjaminPelletier I will try to deploy it from scratch as well between today and tomorrow.

**Comment by mickmis** [comment]
> I apologize; I hadn't realized #909 would cause conflicts with this PR or else I wouldn't have merged it before this one.  Could we do one more merge from master into this branch?  I'll plan not to merge any other PRs before this one.

Sure thing, I will do that tomorrow, so that it should be ready when you start your day :)

**Comment by mickmis** [comment]
> I apologize; I hadn't realized #909 would cause conflicts with this PR or else I wouldn't have merged it before this one. Could we do one more merge from master into this branch? I'll plan not to merge any other PRs before this one.

Now done: #913

**Review by BenjaminPelletier — APPROVED** [review]
I've performed a full deployment on Google Cloud with this version of this branch and everything seems to be working properly.

**Pull request merged**
