### PR TITLE
[monitoring] Test rid_qualifier with Github Actions

### PR DESCRIPTION
**Pull request by barroco**
Part of the effort to reorganize the qualifier to include other services (ie SCD), this PR automates the testing of the qualifier:

1. Starts the mock server
2. Runs the qualifier with the default configuration

The PR introduces Github Actions to run tests.

### CODE REVIEW

**Comment by barroco** [comment]
It looks like Github Actions don't run by default on pull requests from a  forked repository. 

See https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories
> When a first-time contributor submits a pull request to a public repository, a maintainer with write access may need to approve running workflows on the pull request. For more information, see "Approving workflow runs from public forks."

**Comment by BenjaminPelletier** [comment]
This seems good, but I don't see how to run the checks.  I'm [expecting](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork) to see "Workflow(s) awaiting approval" on this Conversation page, but instead I see that "All checks have passed" (and they don't seem to include a GitHub Actions check.  The 6 checks I see as passing are EasyCLA, Trigger: <UUID> (this is the GCP check), and the four Azure interuss.dss (*) variants.

**Comment by barroco** [comment]
After few experiment and research, the workflow needs to exist on the base branch before running for the first time. According to [this page](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories): 

```When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.```

Since the workflow doesn't exist on the base repository yet, the pull_request event has no effect.

**Review by BenjaminPelletier — APPROVED** [review]
I can't effectively evaluate the `.github/workflows` yml file since the workflow won't run until it is part of the base repo, but the tests look good.  Approving to merge and verify action.

**Pull request merged**
